from mpl_toolkits.mplot3d import Axes3D

plt.ion()
plt.show ()
## Tensioni per T2
plt.figure().gca(projection='3d')
delta=20
levels = np.linspace(-1, 1, 40)
plt.title('$\Gamma_{T_2}$ sezione ad H [$N/mm^2$]')
#ali sup
plt.contour(X_pos, Z, tauT2_1sx, delta, zs=0, zdir='z')
plt.contour(X_neg, Z, tauT2_1dx, delta, zs=0, zdir='z')
A1=plt.contourf(X_pos, Z, tauT2_1sx, delta, zs=0, zdir='z' ,cmap='jet',delta)
A2=plt.contourf(X_neg, Z, tauT2_1dx, delta, zs=0, zdir='z' ,cmap='jet',delta)
plt.quiver(X_pos,Z,tauT2_1sx,0*Z,color='k',pivot='tip', units='inches',width=0.01,zdir='y', levels=.0)
plt.quiver(X_neg,Z,-tauT2_1dx,0*Z,color='k',pivot='tip', units='inches',width=0.01,zdir='y', levels=.0)
plt.xlabel(' x  (mm)')
plt.ylabel(' z (mm)')
plt.title('$\Gamma_{xz}$ ali superiori [$N/mm^2$]')
plt.gca().invert_yaxis()
plt.gca().invert_xaxis()
plt.colorbar(A1)
#ali inf
plt.contour(X_pos, Z, -tauT2_3sx, delta)
plt.contour(X_neg, Z, -tauT2_3dx, delta)
B1=plt.contourf(X_pos, Z, -tauT2_3sx, delta,cmap='jet')
B2=plt.contourf(X_neg, Z, -tauT2_3dx, delta,cmap='jet')
plt.quiver(X_pos,Z,tauT2_3sx,0*Z,color='k',pivot='tip', units='inches',width=0.01)
plt.quiver(X_neg,Z,-tauT2_3dx,0*Z,color='k',pivot='tip', units='inches',width=0.01)
plt.xlabel(' x  (mm)')
plt.ylabel(' z (mm)')
plt.title('$\Gamma_{xz}$ ali inferiori [$N/mm^2$]')
plt.gca().invert_yaxis()
plt.gca().invert_xaxis()
plt.colorbar(B1)
#anima
plt.contour(Y, Z, tauT2_2, delta)
C=plt.contourf(Y, Z, tauT2_2, delta,cmap='jet')
plt.quiver(Y,Z,tauT2_2,0*Z,color='k',pivot='tip', units='inches',width=0.01)
plt.title('$\Gamma_{yz}$ anima [$N/mm^2$]')
plt.xlabel(' y  (mm)')
plt.ylabel(' z (mm)')
plt.gca().invert_yaxis()
plt.colorbar(C)